events {}

http {
    server {
        listen 80;

        location /ds-service/ {
            proxy_pass http://ds-service:8010/;
        }

        location /expense-service/ {
            proxy_pass http://expense-service:9820/;
        }

        location /user-service/ {
            proxy_pass http://user-service:9810/;
        }

        location /auth-service/ {
            proxy_pass http://auth-service:9898/;
        }
    }
}